# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - "https://github.com/microsoft/vscode-cpptools/releases/download/1.7.1/cpptools-linux.vsix" 
    - "https://github.com/xpack/vscode-xpack-extension-ts/releases/download/v0.4.16/xpack-0.4.16.vsix"